In [2]:
import numpy as np
import pandas as pd
from pulp import *
import copy

In [3]:
data = pd.read_csv('dataset.csv')
data = data.sort_values(by = 'Unnamed: 0')
ids = data[['Unnamed: 0']]
data = data.drop('Unnamed: 0', axis = 'columns')
data = data.reset_index(drop = True)
data.index = data.index+1
data.index = 'a'+ data.index.astype('str')
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
a1,3,840000.0,13.8,3.0,2.0,2.0,534.0,136.00,1965.0
a2,4,1100000.0,5.9,4.0,2.0,5.0,559.0,195.00,1920.0
a3,2,495000.0,13.9,2.0,1.0,1.0,76.0,79.00,1980.0
a4,3,1120000.0,7.8,3.0,2.0,1.0,293.0,180.00,2006.0
a5,4,2325000.0,9.2,4.0,3.0,2.0,638.0,314.00,1930.0
a6,3,822000.0,13.0,3.0,1.0,4.0,700.0,105.00,1950.0
a7,3,1560000.0,4.6,3.0,2.0,0.0,198.0,148.00,1910.0
a8,2,650000.0,10.5,2.0,1.0,3.0,620.0,85.00,1950.0
a9,3,1223500.0,7.9,3.0,2.0,2.0,721.0,136.00,1980.0
a10,2,790000.0,11.2,2.0,1.0,2.0,196.0,109.00,1970.0
a11,1,440000.0,2.8,1.0,1.0,1.0,0.0,65.00,1920.0
a12,3,923000.0,8.4,3.0,1.0,0.0,221.0,118.00,1900.0
a13,2,1265000.0,2.6,2.0,1.0,0.0,70.0,102.00,1890.0
a14,2,880000.0,3.8,2.0,1.0,2.0,163.0,83.00,1980.0
a15,3,950000.0,3.8,3.0,2.0,2.0,0.0,134.00,2012.0
a16,2,479000.0,2.6,2.0,1.0,1.0,0.0,62.00,1970.0
a17,4,2200000.0,11.2,4.0,2.0,2.0,734.0,272.00,1920.0
a18,4,2440000.0,8.0,4.0,3.0,3.0,500.0,278.00,2005.0
a19,3,1225000.0,8.9,3.0,1.0,1.0,311.0,126.00,1920.0
a20,2,600000.0,5.1,2.0,1.0,1.0,1452.0,96.00,1970.0
a21,3,720000.0,9.5,3.0,2.0,1.0,231.0,145.00,2012.0
a22,3,625000.0,12.4,3.0,1.0,2.0,585.0,88.00,1960.0
a23,3,1035000.0,7.8,3.0,2.0,2.0,275.0,145.00,1920.0
a24,4,1180000.0,14.0,4.0,1.0,2.0,604.0,183.00,1965.0
a25,2,420000.0,9.1,2.0,1.0,1.0,78.0,130.00,1980.0
a26,5,1900000.0,10.7,5.0,3.0,2.0,583.0,271.00,2009.0
a27,6,1455000.0,7.8,6.0,3.0,4.0,768.0,285.00,1997.0
a28,1,365000.0,7.4,1.0,1.0,1.0,0.0,46.00,1960.0
a29,3,1300000.0,5.5,3.0,1.0,0.0,191.0,108.00,1915.0
a30,3,1190000.0,8.8,3.0,2.0,2.0,572.0,118.00,1935.0
a31,3,680000.0,2.1,3.0,2.0,2.0,0.0,110.87,2003.0
a32,4,521000.0,45.9,4.0,2.0,2.0,978.0,144.00,1980.0
a33,2,645000.0,16.0,2.0,1.0,1.0,105.0,64.00,1970.0
a34,3,1175000.0,10.5,3.0,1.0,3.0,284.0,120.00,1970.0
a35,3,600000.0,14.8,3.0,1.0,3.0,406.0,196.00,2005.0
a36,2,1100000.0,16.7,2.0,1.0,1.0,258.0,106.00,1980.0
a37,4,732000.0,17.9,3.0,2.0,1.0,808.0,184.00,1980.0
a38,3,877000.0,17.9,3.0,1.0,2.0,533.0,135.00,1965.0
a39,3,860000.0,23.5,3.0,2.0,2.0,537.0,220.00,2001.0
a40,4,870000.0,14.8,4.0,2.0,2.0,463.0,307.00,2012.0
a41,3,815000.0,16.1,3.0,2.0,2.0,609.0,168.00,1980.0
a42,4,1350000.0,5.2,4.0,2.0,1.0,372.0,184.00,1920.0
a43,1,361000.0,7.8,1.0,1.0,1.0,60.0,53.00,1975.0
a44,3,828000.0,14.3,3.0,2.0,2.0,301.0,117.00,1980.0
a45,3,485000.0,20.6,3.0,2.0,1.0,321.0,150.00,2013.0
a46,3,1307500.0,7.3,3.0,1.0,1.0,316.0,111.00,1940.0
a47,2,653000.0,10.9,2.0,1.0,1.0,84.0,77.00,1970.0
a48,2,1300000.0,2.1,2.0,1.0,1.0,125.0,124.00,2000.0
a49,4,1450000.0,15.5,4.0,2.0,2.0,771.0,196.00,1970.0
a50,3,1400000.0,10.1,3.0,2.0,3.0,818.0,193.00,2011.0

In [3]:
data.describe()

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
count,50.000000,5.000000e+01,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,2.940000,1.010540e+06,10.760000,2.920000,1.580000,1.72000,400.440000,146.037400,1966.520000
std,0.977502,4.836915e+05,7.117727,0.965528,0.641745,1.03095,305.460586,67.062725,33.749522
min,1.000000,3.610000e+05,2.100000,1.000000,1.000000,0.00000,0.000000,46.000000,1890.000000
25%,2.000000,6.507500e+05,7.325000,2.000000,1.000000,1.00000,170.000000,105.250000,1942.500000
50%,3.000000,8.785000e+05,9.350000,3.000000,1.500000,2.00000,318.500000,132.000000,1970.000000
75%,3.000000,1.255000e+06,13.975000,3.000000,2.000000,2.00000,599.250000,183.750000,1992.750000
max,6.000000,2.440000e+06,45.900000,6.000000,3.000000,5.00000,1452.000000,314.000000,2013.000000

## **1. UTA algorithm - finding minimal subset of inconsistent constraints** ##

In [227]:
# preference_list - list of pairs (better, worse)
preference_list = [("a4", "a9"), ("a9", "a13"), ("a13", "a4"), ("a4", "a1"), ("a45", "a32"), 
("a27", "a18"), ("a25", "a28"), ("a45", "a50"), ("a43", "a37"), ("a39", "a38"), 
("a31", "a33"), ("a30", "a42"), ("a40", "a35"), ("a27", "a26"), ("a3", "a11"), 
("a6", "a7"), ("a21", "a2"), ("a15", "a12"), ("a20", "a29"), ("a41", "a24"), 
("a23", "a34"), ("a5", "a18"), ("a8", "a14"), ("a10", "a19"), ("a22", "a16"),
("a49", "a44"), ("a36", "a48"), ("a47", "a46"),("a1", "a13"), ("a21", "a12"),
("a27", "a17"), ("a43", "a28"), ("a50", "a49"), ("a25", "a16"), ("a4", "a16"),
("a8", "a11"), ("a20", "a13"), ("a26", "a5"), ("a32", "a33"), ("a40", "a33"),
("a8", "a6"), ("a1", "a11"), ("a11", "a13"), ("a45", "a41"), ("a21", "a23"),
("a18", "a7"), ("a24", "a19"), ("a27", "a21"), ("a39", "a30"), ("a49", "a23")]

# Inconsistencies: cycle a4, a9, a13

In [228]:
# criteria_types - list of pairs in form (gain or cost type, is discrete?)
criteria_types = [('gain', True), ('cost', False), 
('cost', False), ('gain', True), ('gain', True), 
('gain', True), ('gain', False), ('gain', False), 
('gain', False)]

In [213]:
def build_uta_model(preference_list, df, criteria_types):
    # 0. Define Linear Problem - we want to minimize number of const that are excluded
    model = LpProblem('uta_model', LpMinimize)
    eps = 0.001

    pairwise_comparisons = copy.deepcopy(preference_list)
    binary_variables = LpVariable.dicts('bin_var', pairwise_comparisons, cat='Binary')
    model += lpSum(list(binary_variables.values()))

    # 1. Add weights const
    weights = []
    for crit in df.columns:
        weights.append(LpVariable(f'w_{crit}', lowBound = 1/(5*len(df.columns)), upBound = 0.5, cat = 'Continuous'))

    # 2. Add norm const
    model += lpSum(weights) == 1

    # 3. Utility constraints
    utility_vars = {}
    for alt in df.index:
        for criterion in df.columns:
            curr_util_name = 'u_'+alt+'_'+criterion
            utility_vars[curr_util_name] = LpVariable(curr_util_name, lowBound=0, cat = 'Continuous')
    
    for i in range(len(criteria_types)):
        # Find best and worst
        if criteria_types[i][0] == 'cost':
            best_idx = np.argmin(df[df.columns[i]])
            worst_idx = np.argmax(df[df.columns[i]])
        else:
            worst_idx = np.argmin(df[df.columns[i]])
            best_idx = np.argmax(df[df.columns[i]])

        model += utility_vars[f'u_{df.index[best_idx]}_{df.columns[i]}'] == 1
        model += utility_vars[f'u_{df.index[worst_idx]}_{df.columns[i]}'] == 0

        # Monocity constraint
        if criteria_types[i][0] == 'cost':
            sorted_alts = np.argsort(df[df.columns[i]])
        else:
            sorted_alts = np.argsort(df[df.columns[i]])[::-1]
        for j in range(len(sorted_alts)-1):
                model += utility_vars[f'u_{df.index[sorted_alts[j]]}_{df.columns[i]}'] >= utility_vars[f'u_{df.index[sorted_alts[j+1]]}_{df.columns[i]}']
    print(model)

    # 4. Add utility functions
    for better, worse in pairwise_comparisons:
        # if criterion can't be met, then 1 is substracted on the right side so that it holds
        model += lpSum([weights[i] * utility_vars[f'u_{better}_{df.columns[i]}'] for i in range(len(weights))]) > lpSum([weights[i] * utility_vars[f'u_{worse}_{df.columns[i]}'] for i in range(len(weights))]) - binary_vars[(alt1, alt2)] + eps
    print(model)
    return model

In [214]:
def build_uta_model_2_1(preference_list, df, criteria_types):
    model = LpProblem('uta_model', LpMinimize)
    eps = 0.001

    # 0. Add binary variables for each pairwise preference
    pairwise_comparisons = copy.deepcopy(preference_list)
    binary_variables = LpVariable.dicts('bin_var', pairwise_comparisons, cat='Binary')
    model += lpSum(list(binary_variables.values()))

    # 1. Add weights
    weights = {}
    n_criteria = len(df.columns)
    for crit in df.columns:
        weights[crit] = LpVariable(f'w_{crit}', lowBound=1/(5*n_criteria), upBound=0.5, cat='Continuous')

    # 2. Add normalization constraint
    model += lpSum(weights.values()) == 1

    # 3. Utility values for each alternative per criterion (constants here)
    # Normalize criterion values between 0 and 1
    normalized_df = df.copy()
    for crit, (ctype, isDiscrete) in zip(df.columns, criteria_types):
        if ctype == 'cost':
            normalized_df[crit] = (df[crit].max() - df[crit]) / (df[crit].max() - df[crit].min())
        else:
            normalized_df[crit] = (df[crit] - df[crit].min()) / (df[crit].max() - df[crit].min())

    # Total utility for each alternative
    U = {}
    for alt in df.index:
        U[alt] = LpVariable(f'U_{alt}', lowBound=0, upBound=1, cat='Continuous')
        model += U[alt] == lpSum([weights[crit] * normalized_df.loc[alt, crit] for crit in df.columns])

    # 4. Pairwise constraints (some may be rejected by binary variables)
    for (alt1, alt2) in pairwise_comparisons:
        model += U[alt1] >= U[alt2] + eps - binary_variables[(alt1, alt2)]

    return model

In [229]:
def compute_breakpoints(values, num_breakpoints):
    """Compute equally spaced breakpoints over a criterion’s value range."""
    min_val, max_val = np.min(values), np.max(values)
    return np.linspace(min_val, max_val, num_breakpoints)

In [230]:
def build_uta_model_with_piecewise(preference_list, df, criteria_types, num_breakpoints=6):
    model = LpProblem('UTA_Model_Piecewise', LpMinimize)
    eps = 0.01

    alternatives = df.index.tolist()
    criteria = df.columns.tolist()
    n_criteria = len(criteria)

    # 1a Define weights
    weights = {
        crit: LpVariable(f'w_{crit}', lowBound=1 / (5 * n_criteria), upBound=0.5, cat='Continuous')
        for crit in criteria
    }

    # 1b Normalization constraint
    model += lpSum([weights[i] for i in df.columns]) == 1

    # 2. Define breakpoints and lambda values
    breakpoints = {crit: compute_breakpoints(df[crit], num_breakpoints) for crit in criteria}
    lambdas = {
        (crit, k): LpVariable(f'lambda_{crit}_{k}', lowBound=0, upBound=1, cat='Continuous')
        for crit in criteria for k in range(num_breakpoints)
    }

    for i in range(len(criteria_types)):
        if criteria_types[i][0] == 'cost':
            model += lambdas[(criteria[i], 0)] == 1
            model += lambdas[(criteria[i], num_breakpoints - 1)] == 0
            for k in range(num_breakpoints - 1):
                model += lambdas[(criteria[i], k)] >= lambdas[(criteria[i], k + 1)]
        else:
            model += lambdas[(criteria[i], 0)] == 0
            model += lambdas[(criteria[i], num_breakpoints - 1)] == 1
            for k in range(num_breakpoints - 1):
                model += lambdas[(criteria[i], k)] <= lambdas[(criteria[i], k + 1)]

    # 3. Interpolation weights
    interpolation_weights = {}
    for alt in alternatives:
        for crit in criteria:
            val = df.loc[alt, crit]
            bp = breakpoints[crit]
            for k in range(num_breakpoints - 1):
                if bp[k] <= val <= bp[k + 1]:
                    alpha = (val - bp[k]) / (bp[k + 1] - bp[k]) if bp[k + 1] != bp[k] else 0
                    interpolation_weights[(alt, crit)] = (k, 1 - alpha, alpha)
                    break

    # 4. Define U(alt) as sum of weighted marginal utilities
    U = {
        alt: LpVariable(f'U_{alt}', lowBound=0, upBound=1, cat='Continuous')
        for alt in alternatives
    }

    for alt in alternatives:
        weighted_sum_expr = []
        for crit in criteria:
            k, beta1, beta2 = interpolation_weights[(alt, crit)]
            marginal = beta1 * lambdas[(crit, k)] + beta2 * lambdas[(crit, k + 1)]

            # New variable for marginal utility
            u_crit = LpVariable(f'u_{alt}_{crit}', lowBound=0, upBound=1)
            model += u_crit == marginal

            # New variable for weighted utility
            wu = LpVariable(f'wu_{alt}_{crit}', lowBound=0, upBound=1)

            # Linearization of wu = w * u
            model += wu <= weights[crit]
            model += wu <= u_crit
            model += wu >= weights[crit] + u_crit - 1
            # model += wu >= 0

            weighted_sum_expr.append(wu)

        model += U[alt] == lpSum(weighted_sum_expr)

    # 5. Preference constraints with slack variables
    binary_vars = {
        (a1, a2): LpVariable(f'z_{a1}_{a2}', cat='Binary')
        for (a1, a2) in preference_list
    }
    model += lpSum(binary_vars.values())  # objective

    for (a1, a2) in preference_list:
        model += U[a1] >= U[a2] + eps - binary_vars[(a1, a2)]
    return model

In [231]:
model = build_uta_model_with_piecewise(preference_list, data, criteria_types)
status = model.solve(solver = GLPK())

GLPSOL--GLPK LP/MIP Solver 5.0
Parameter(s) specified in the command line:
 --cpxlp /var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ad460e4d478b4dcd9980992a00e4632a-pulp.lp
 -o /var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ad460e4d478b4dcd9980992a00e4632a-pulp.sol
Reading problem data from '/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ad460e4d478b4dcd9980992a00e4632a-pulp.lp'...
1964 rows, 1063 columns, 5073 non-zeros
50 integer variables, all of which are binary
3378 lines were read
GLPK Integer Optimizer 5.0
1964 rows, 1063 columns, 5073 non-zeros
50 integer variables, all of which are binary
Preprocessing...
1715 rows, 944 columns, 4390 non-zeros
50 integer variables, all of which are binary
Scaling...
 A: min|aij| =  4.566e-03  max|aij| =  1.000e+00  ratio =  2.190e+02
GM: min|aij| =  1.198e-01  max|aij| =  8.344e+00  ratio =  6.962e+01
EQ: min|aij| =  1.436e-02  max|aij| =  1.000e+00  ratio =  6.962e+01
2N: min|aij| =  7.937e-03  max|aij| =  1.727e+00  ratio =  2.176e+02
Constructing initial basis...
Size of triangular part is 1715
Solving LP relaxation...
GLPK Simplex Optimizer 5.0
1715 rows, 944 columns, 4390 non-zeros
      0: obj =   0.000000000e+00 inf =   8.751e+00 (77)
    102: obj =   5.513064471e-01 inf =   2.914e-16 (0)
*   181: obj =   4.000000000e-02 inf =   1.110e-16 (0) 1
OPTIMAL LP SOLUTION FOUND
Integer optimization begins...
Long-step dual simplex will be used
+   181: mip =     not found yet >=              -inf        (1; 0)
+   209: >>>>>   1.000000000e+00 >=   1.000000000e+00   0.0% (2; 0)
+   209: mip =   1.000000000e+00 >=     tree is empty   0.0% (0; 3)
INTEGER OPTIMAL SOLUTION FOUND
Time used:   0.0 secs
Memory used: 2.6 Mb (2693378 bytes)
Writing MIP solution to '/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/ad460e4d478b4dcd9980992a00e4632a-pulp.sol'...

In [232]:
print("status:", model.status, LpStatus[model.status])
print("objective:", model.objective.value())

status: 1 Optimal
objective: 1

In [233]:
for var in model.variables():
    if 'z_' in var.name and var.value() > 0:
        print(var.name, var.value(), "is inconsistent")
    # else:
    #     print(var.name, var.value())

z_a13_a4 1 is inconsistent

## **UTA 2.2** ##

In [234]:
consistent_preference_list = list(set(preference_list).difference({('a13', 'a4')}))

In [235]:
consistent_preference_list

[('a31', 'a33'),
 ('a40', 'a35'),
 ('a45', 'a32'),
 ('a49', 'a23'),
 ('a39', 'a38'),
 ('a3', 'a11'),
 ('a5', 'a18'),
 ('a47', 'a46'),
 ('a45', 'a50'),
 ('a15', 'a12'),
 ('a30', 'a42'),
 ('a4', 'a1'),
 ('a6', 'a7'),
 ('a27', 'a17'),
 ('a27', 'a26'),
 ('a18', 'a7'),
 ('a21', 'a12'),
 ('a21', 'a2'),
 ('a4', 'a9'),
 ('a20', 'a13'),
 ('a21', 'a23'),
 ('a50', 'a49'),
 ('a36', 'a48'),
 ('a40', 'a33'),
 ('a1', 'a11'),
 ('a10', 'a19'),
 ('a24', 'a19'),
 ('a25', 'a16'),
 ('a20', 'a29'),
 ('a43', 'a37'),
 ('a11', 'a13'),
 ('a23', 'a34'),
 ('a8', 'a11'),
 ('a4', 'a16'),
 ('a39', 'a30'),
 ('a32', 'a33'),
 ('a9', 'a13'),
 ('a27', 'a18'),
 ('a8', 'a6'),
 ('a1', 'a13'),
 ('a43', 'a28'),
 ('a45', 'a41'),
 ('a22', 'a16'),
 ('a26', 'a5'),
 ('a25', 'a28'),
 ('a49', 'a44'),
 ('a8', 'a14'),
 ('a27', 'a21'),
 ('a41', 'a24')]

In [236]:
def build_uta_model_2_2(preference_list, df, criteria_types, num_breakpoints = 6):
    model = LpProblem('UTA_Model_max_distance', LpMaximize)
    eps = 0.001

    alternatives = df.index.tolist()
    criteria = df.columns.tolist()
    n_criteria = len(criteria)

    # 1a Define weights
    weights = {
        crit: LpVariable(f'w_{crit}', lowBound=1 / (5 * n_criteria), upBound=0.5, cat='Continuous')
        for crit in criteria
    }

    # 1b Normalization constraint
    model += lpSum([weights[i] for i in df.columns]) == 1

    # 2. Define breakpoints and lambda values
    breakpoints = {crit: compute_breakpoints(df[crit], num_breakpoints) for crit in criteria}
    lambdas = {
        (crit, k): LpVariable(f'lambda_{crit}_{k}', lowBound=0, upBound=1, cat='Continuous')
        for crit in criteria for k in range(num_breakpoints)
    }

    for i in range(len(criteria_types)):
        if criteria_types[i][0] == 'cost':
            model += lambdas[(criteria[i], 0)] == 1
            model += lambdas[(criteria[i], num_breakpoints - 1)] == 0
            for k in range(num_breakpoints - 1):
                model += lambdas[(criteria[i], k)] >= lambdas[(criteria[i], k + 1)] + 0.1
        else:
            model += lambdas[(criteria[i], 0)] == 0
            model += lambdas[(criteria[i], num_breakpoints - 1)] == 1
            for k in range(num_breakpoints - 1):
                model += lambdas[(criteria[i], k)] + 0.1 <= lambdas[(criteria[i], k + 1)]

    # 3. Interpolation weights
    interpolation_weights = {}
    for alt in alternatives:
        for crit in criteria:
            val = df.loc[alt, crit]
            bp = breakpoints[crit]
            for k in range(num_breakpoints - 1):
                if bp[k] <= val <= bp[k + 1]:
                    alpha = (val - bp[k]) / (bp[k + 1] - bp[k]) if bp[k + 1] != bp[k] else 0
                    interpolation_weights[(alt, crit)] = (k, 1 - alpha, alpha)
                    break

    # 4. Define U(alt) as sum of weighted marginal utilities
    U = {
        alt: LpVariable(f'U_{alt}', lowBound=0, upBound=1, cat='Continuous')
        for alt in alternatives
    }

    for alt in alternatives:
        weighted_sum_expr = []
        for crit in criteria:
            k, beta1, beta2 = interpolation_weights[(alt, crit)]
            marginal = beta1 * lambdas[(crit, k)] + beta2 * lambdas[(crit, k + 1)]

            # New variable for marginal utility
            u_crit = LpVariable(f'u_{alt}_{crit}', lowBound=0, upBound=1)
            model += u_crit == marginal

            # New variable for weighted utility
            wu = LpVariable(f'wu_{alt}_{crit}', lowBound=0, upBound=1)

            # Linearization of wu = w * u
            model += wu <= weights[crit]
            model += wu <= u_crit
            model += wu >= weights[crit] + u_crit - 1
            # model += wu >= 0

            weighted_sum_expr.append(wu)

        model += U[alt] == lpSum(weighted_sum_expr)

    # 5. Objective function:
    obj = []
    for (a1, a2) in preference_list:
        obj.append(U[a1] - U[a2])
    model += lpSum(obj) # objective

    # 6. Preference relations
    for (a1, a2) in preference_list:
        model += U[a1] >= U[a2] + eps

    return model

In [237]:
model2 = build_uta_model_2_2(consistent_preference_list, data, criteria_types)
status = model2.solve(solver = GLPK())

GLPSOL--GLPK LP/MIP Solver 5.0
Parameter(s) specified in the command line:
 --cpxlp /var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/0fcb84de154f461bb84ecc4b16c30410-pulp.lp
 -o /var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/0fcb84de154f461bb84ecc4b16c30410-pulp.sol
Reading problem data from '/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/0fcb84de154f461bb84ecc4b16c30410-pulp.lp'...
1963 rows, 1013 columns, 5021 non-zeros
3324 lines were read
GLPK Simplex Optimizer 5.0
1963 rows, 1013 columns, 5021 non-zeros
Preprocessing...
1725 rows, 894 columns, 4371 non-zeros
Scaling...
 A: min|aij| =  4.566e-03  max|aij| =  1.000e+00  ratio =  2.190e+02
GM: min|aij| =  1.198e-01  max|aij| =  8.344e+00  ratio =  6.962e+01
EQ: min|aij| =  1.436e-02  max|aij| =  1.000e+00  ratio =  6.962e+01
Constructing initial basis...
Size of triangular part is 1725
      0: obj =  -0.000000000e+00 inf =   1.268e+01 (103)
    111: obj =   3.987395664e+00 inf =   1.249e-16 (0)
*   336: obj =   3.269221745e+01 inf =   3.101e-16 (0) 1
OPTIMAL LP SOLUTION FOUND
Time used:   0.0 secs
Memory used: 2.2 Mb (2275013 bytes)
Writing basic solution to '/var/folders/8m/nx_b_wh17dg77b9kb95gxng80000gp/T/0fcb84de154f461bb84ecc4b16c30410-pulp.sol'...

In [238]:
print("status:", model2.status, LpStatus[model2.status])
print("objective:", model2.objective.value())

status: 1 Optimal
objective: 32.69221980000001

In [239]:
for var in model2.variables():
    print(var.name, var.value())

U_a1 0.999
U_a10 0.977778
U_a11 0.001
U_a12 0.0
U_a13 0.0
U_a14 0.0
U_a15 0.977778
U_a16 0.0
U_a17 0.0
U_a18 0.0710027
U_a19 0.0
U_a2 0.4
U_a20 0.977778
U_a21 0.999
U_a22 0.977778
U_a23 0.001
U_a24 0.001
U_a25 0.977778
U_a26 0.26236
U_a27 1.0
U_a28 0.0164502
U_a29 0.0
U_a3 0.977778
U_a30 0.001
U_a31 0.977778
U_a32 0.243902
U_a33 0.0
U_a34 0.0
U_a35 0.0487805
U_a36 0.977778
U_a37 0.0
U_a38 0.0
U_a39 1.0
U_a4 1.0
U_a40 1.0
U_a41 0.002
U_a42 0.0
U_a43 0.799129
U_a44 0.0
U_a45 1.0
U_a46 0.0
U_a47 0.977778
U_a48 0.0342466
U_a49 0.998
U_a5 0.26136
U_a50 0.999
U_a6 0.343902
U_a7 0.0
U_a8 0.977778
U_a9 0.243902
lambda_Bathroom_0 0.0
lambda_Bathroom_1 0.1
lambda_Bathroom_2 0.2
lambda_Bathroom_3 0.3
lambda_Bathroom_4 0.4
lambda_Bathroom_5 1.0
lambda_Bedroom2_0 0.0
lambda_Bedroom2_1 0.1
lambda_Bedroom2_2 0.2
lambda_Bedroom2_3 0.3
lambda_Bedroom2_4 0.4
lambda_Bedroom2_5 1.0
lambda_BuildingArea_0 0.0
lambda_BuildingArea_1 0.586047
lambda_BuildingArea_2 0.686047
lambda_BuildingArea_3 0.786047
lambda_BuildingArea_4 0.886047
lambda_BuildingArea_5 1.0
lambda_Car_0 0.0
lambda_Car_1 0.4
lambda_Car_2 0.5
lambda_Car_3 0.6
lambda_Car_4 0.7
lambda_Car_5 1.0
lambda_Distance_0 1.0
lambda_Distance_1 0.4
lambda_Distance_2 0.3
lambda_Distance_3 0.2
lambda_Distance_4 0.1
lambda_Distance_5 0.0
lambda_Landsize_0 0.0
lambda_Landsize_1 0.107556
lambda_Landsize_2 0.207556
lambda_Landsize_3 0.307556
lambda_Landsize_4 0.407556
lambda_Landsize_5 1.0
lambda_Price_0 1.0
lambda_Price_1 0.4
lambda_Price_2 0.3
lambda_Price_3 0.2
lambda_Price_4 0.1
lambda_Price_5 0.0
lambda_Rooms_0 0.0
lambda_Rooms_1 0.156426
lambda_Rooms_2 0.7
lambda_Rooms_3 0.8
lambda_Rooms_4 0.9
lambda_Rooms_5 1.0
lambda_YearBuilt_0 0.0
lambda_YearBuilt_1 0.1
lambda_YearBuilt_2 0.2
lambda_YearBuilt_3 0.3
lambda_YearBuilt_4 0.4
lambda_YearBuilt_5 1.0
u_a10_Bathroom 0.0
u_a10_Bedroom2 0.1
u_a10_BuildingArea 0.603584
u_a10_Car 0.5
u_a10_Distance 0.396119
u_a10_Landsize 0.0725926
u_a10_Price 0.396825
u_a10_Rooms 0.156426
u_a10_YearBuilt 0.325203
u_a11_Bathroom 0.0
u_a11_Bedroom2 0.0
u_a11_BuildingArea 0.20774
u_a11_Car 0.4
u_a11_Distance 0.952055
u_a11_Landsize 0.0
u_a11_Price 0.886003
u_a11_Rooms 0.0
u_a11_YearBuilt 0.121951
u_a12_Bathroom 0.0
u_a12_Bedroom2 0.2
u_a12_BuildingArea 0.620375
u_a12_Car 0.0
u_a12_Distance 0.568493
u_a12_Landsize 0.0818519
u_a12_Price 0.364839
u_a12_Rooms 0.7
u_a12_YearBuilt 0.0406504
u_a13_Bathroom 0.0
u_a13_Bedroom2 0.1
u_a13_BuildingArea 0.590524
u_a13_Car 0.0
u_a13_Distance 0.965753
u_a13_Landsize 0.0259259
u_a13_Price 0.282588
u_a13_Rooms 0.156426
u_a13_YearBuilt 0.0
u_a14_Bathroom 0.0
u_a14_Bedroom2 0.1
u_a14_BuildingArea 0.404547
u_a14_Car 0.5
u_a14_Distance 0.883562
u_a14_Landsize 0.0603704
u_a14_Price 0.37518
u_a14_Rooms 0.156426
u_a14_YearBuilt 0.365854
u_a15_Bathroom 0.25
u_a15_Bedroom2 0.2
u_a15_BuildingArea 0.650226
u_a15_Car 0.5
u_a15_Distance 0.883562
u_a15_Landsize 0.0
u_a15_Price 0.358345
u_a15_Rooms 0.7
u_a15_YearBuilt 0.97561
u_a16_Bathroom 0.0
u_a16_Bedroom2 0.1
u_a16_BuildingArea 0.174939
u_a16_Car 0.4
u_a16_Distance 0.965753
u_a16_Landsize 0.0
u_a16_Price 0.829726
u_a16_Rooms 0.156426
u_a16_YearBuilt 0.325203
u_a17_Bathroom 0.25
u_a17_Bedroom2 0.3
u_a17_BuildingArea 0.910708
u_a17_Car 0.5
u_a17_Distance 0.396119
u_a17_Landsize 0.26031
u_a17_Price 0.0577201
u_a17_Rooms 0.8
u_a17_YearBuilt 0.121951
u_a18_Bathroom 1.0
u_a18_Bedroom2 0.3
u_a18_BuildingArea 0.923464
u_a18_Car 0.6
u_a18_Distance 0.59589
u_a18_Landsize 0.179732
u_a18_Price 0.0
u_a18_Rooms 0.8
u_a18_YearBuilt 0.804878
u_a19_Bathroom 0.0
u_a19_Bedroom2 0.2
u_a19_BuildingArea 0.6353
u_a19_Car 0.4
u_a19_Distance 0.534247
u_a19_Landsize 0.114649
u_a19_Price 0.292208
u_a19_Rooms 0.7
u_a19_YearBuilt 0.121951
u_a1_Bathroom 0.25
u_a1_Bedroom2 0.2
u_a1_BuildingArea 0.653957
u_a1_Car 0.5
u_a1_Distance 0.366438
u_a1_Landsize 0.19144
u_a1_Price 0.3848
u_a1_Rooms 0.7
u_a1_YearBuilt 0.304878
u_a20_Bathroom 0.0
u_a20_Bedroom2 0.1
u_a20_BuildingArea 0.546685
u_a20_Car 0.4
u_a20_Distance 0.794521
u_a20_Landsize 1.0
u_a20_Price 0.655123
u_a20_Rooms 0.156426
u_a20_YearBuilt 0.325203
u_a21_Bathroom 0.25
u_a21_Bedroom2 0.2
u_a21_BuildingArea 0.670748
u_a21_Car 0.4
u_a21_Distance 0.493151
u_a21_Landsize 0.0855556
u_a21_Price 0.481962
u_a21_Rooms 0.7
u_a21_YearBuilt 0.97561
u_a22_Bathroom 0.0
u_a22_Bedroom2 0.2
u_a22_BuildingArea 0.459216
u_a22_Car 0.5
u_a22_Distance 0.38242
u_a22_Landsize 0.209002
u_a22_Price 0.619048
u_a22_Rooms 0.7
u_a22_YearBuilt 0.284553
u_a23_Bathroom 0.25
u_a23_Bedroom2 0.2
u_a23_BuildingArea 0.670748
u_a23_Car 0.5
u_a23_Distance 0.609589
u_a23_Landsize 0.101852
u_a23_Price 0.337903
u_a23_Rooms 0.7
u_a23_YearBuilt 0.121951
u_a24_Bathroom 0.0
u_a24_Bedroom2 0.3
u_a24_BuildingArea 0.741644
u_a24_Car 0.5
u_a24_Distance 0.364155
u_a24_Landsize 0.215545
u_a24_Price 0.30303
u_a24_Rooms 0.8
u_a24_YearBuilt 0.304878
u_a25_Bathroom 0.0
u_a25_Bedroom2 0.1
u_a25_BuildingArea 0.642763
u_a25_Car 0.4
u_a25_Distance 0.520548
u_a25_Landsize 0.0288889
u_a25_Price 0.914863
u_a25_Rooms 0.156426
u_a25_YearBuilt 0.365854
u_a26_Bathroom 1.0
u_a26_Bedroom2 0.4
u_a26_BuildingArea 0.908582
u_a26_Car 0.5
u_a26_Distance 0.410959
u_a26_Landsize 0.208313
u_a26_Price 0.12987
u_a26_Rooms 0.9
u_a26_YearBuilt 0.902439
u_a27_Bathroom 1.0
u_a27_Bedroom2 1.0
u_a27_BuildingArea 0.938346
u_a27_Car 0.7
u_a27_Distance 0.609589
u_a27_Landsize 0.272018
u_a27_Price 0.236893
u_a27_Rooms 1.0
u_a27_YearBuilt 0.609756
u_a28_Bathroom 0.0
u_a28_Bedroom2 0.0
u_a28_BuildingArea 0.0
u_a28_Car 0.4
u_a28_Distance 0.636986
u_a28_Landsize 0.0
u_a28_Price 0.994228
u_a28_Rooms 0.0
u_a28_YearBuilt 0.284553
u_a29_Bathroom 0.0
u_a29_Bedroom2 0.2
u_a29_BuildingArea 0.601718
u_a29_Car 0.0
u_a29_Distance 0.767123
u_a29_Landsize 0.0707407
u_a29_Price 0.27417
u_a29_Rooms 0.7
u_a29_YearBuilt 0.101626
u_a2_Bathroom 0.25
u_a2_Bedroom2 0.3
u_a2_BuildingArea 0.764032
u_a2_Car 1.0
u_a2_Distance 0.739726
u_a2_Landsize 0.200049
u_a2_Price 0.32227
u_a2_Rooms 0.8
u_a2_YearBuilt 0.121951
u_a30_Bathroom 0.25
u_a30_Bedroom2 0.2
u_a30_BuildingArea 0.620375
u_a30_Car 0.5
u_a30_Distance 0.541096
u_a30_Landsize 0.204525
u_a30_Price 0.300625
u_a30_Rooms 0.7
u_a30_YearBuilt 0.182927
u_a31_Bathroom 0.25
u_a31_Bedroom2 0.2
u_a31_BuildingArea 0.607073
u_a31_Car 0.5
u_a31_Distance 1.0
u_a31_Landsize 0.0
u_a31_Price 0.539683
u_a31_Rooms 0.7
u_a31_YearBuilt 0.756098
u_a32_Bathroom 0.25
u_a32_Bedroom2 0.3
u_a32_BuildingArea 0.668882
u_a32_Car 0.5
u_a32_Distance 0.0
u_a32_Landsize 0.344332
u_a32_Price 0.76912
u_a32_Rooms 0.8
u_a32_YearBuilt 0.365854
u_a33_Bathroom 0.0
u_a33_Bedroom2 0.1
u_a33_BuildingArea 0.196807
u_a33_Car 0.4
u_a33_Distance 0.341324
u_a33_Landsize 0.0388889
u_a33_Price 0.590188
u_a33_Rooms 0.156426
u_a33_YearBuilt 0.325203
u_a34_Bathroom 0.0
u_a34_Bedroom2 0.2
u_a34_BuildingArea 0.624106
u_a34_Car 0.6
u_a34_Distance 0.424658
u_a34_Landsize 0.105185
u_a34_Price 0.304233
u_a34_Rooms 0.7
u_a34_YearBuilt 0.325203
u_a35_Bathroom 0.0
u_a35_Bedroom2 0.2
u_a35_BuildingArea 0.765897
u_a35_Car 0.6
u_a35_Distance 0.355023
u_a35_Landsize 0.147363
u_a35_Price 0.655123
u_a35_Rooms 0.7
u_a35_YearBuilt 0.804878
u_a36_Bathroom 0.0
u_a36_Bedroom2 0.1
u_a36_BuildingArea 0.597987
u_a36_Car 0.4
u_a36_Distance 0.333333
u_a36_Landsize 0.0955556
u_a36_Price 0.32227
u_a36_Rooms 0.156426
u_a36_YearBuilt 0.365854
u_a37_Bathroom 0.25
u_a37_Bedroom2 0.2
u_a37_BuildingArea 0.743509
u_a37_Car 0.4
u_a37_Distance 0.319635
u_a37_Landsize 0.285792
u_a37_Price 0.464646
u_a37_Rooms 0.8
u_a37_YearBuilt 0.365854
u_a38_Bathroom 0.0
u_a38_Bedroom2 0.2
u_a38_BuildingArea 0.652091
u_a38_Car 0.5
u_a38_Distance 0.319635
u_a38_Landsize 0.191096
u_a38_Price 0.375902
u_a38_Rooms 0.7
u_a38_YearBuilt 0.304878
u_a39_Bathroom 0.25
u_a39_Bedroom2 0.2
u_a39_BuildingArea 0.810673
u_a39_Car 0.5
u_a39_Distance 0.255708
u_a39_Landsize 0.192473
u_a39_Price 0.37999
u_a39_Rooms 0.7
u_a39_YearBuilt 0.707317
u_a3_Bathroom 0.0
u_a3_Bedroom2 0.1
u_a3_BuildingArea 0.360812
u_a3_Car 0.4
u_a3_Distance 0.365297
u_a3_Landsize 0.0281481
u_a3_Price 0.806638
u_a3_Rooms 0.156426
u_a3_YearBuilt 0.365854
u_a40_Bathroom 0.25
u_a40_Bedroom2 0.3
u_a40_BuildingArea 0.985118
u_a40_Car 0.5
u_a40_Distance 0.355023
u_a40_Landsize 0.166991
u_a40_Price 0.377585
u_a40_Rooms 0.8
u_a40_YearBuilt 0.97561
u_a41_Bathroom 0.25
u_a41_Bedroom2 0.2
u_a41_BuildingArea 0.713658
u_a41_Car 0.5
u_a41_Distance 0.340183
u_a41_Landsize 0.217266
u_a41_Price 0.390813
u_a41_Rooms 0.7
u_a41_YearBuilt 0.365854
u_a42_Bathroom 0.25
u_a42_Bedroom2 0.3
u_a42_BuildingArea 0.743509
u_a42_Car 0.4
u_a42_Distance 0.787671
u_a42_Landsize 0.135655
u_a42_Price 0.262145
u_a42_Rooms 0.8
u_a42_YearBuilt 0.121951
u_a43_Bathroom 0.0
u_a43_Bedroom2 0.0
u_a43_BuildingArea 0.0765359
u_a43_Car 0.4
u_a43_Distance 0.609589
u_a43_Landsize 0.0222222
u_a43_Price 1.0
u_a43_Rooms 0.0
u_a43_YearBuilt 0.345528
u_a44_Bathroom 0.25
u_a44_Bedroom2 0.2
u_a44_BuildingArea 0.618509
u_a44_Car 0.5
u_a44_Distance 0.360731
u_a44_Landsize 0.111206
u_a44_Price 0.387686
u_a44_Rooms 0.7
u_a44_YearBuilt 0.365854
u_a45_Bathroom 0.25
u_a45_Bedroom2 0.2
u_a45_BuildingArea 0.680076
u_a45_Car 0.4
u_a45_Distance 0.288813
u_a45_Landsize 0.118093
u_a45_Price 0.821068
u_a45_Rooms 0.7
u_a45_YearBuilt 1.0
u_a46_Bathroom 0.0
u_a46_Bedroom2 0.2
u_a46_BuildingArea 0.607315
u_a46_Car 0.4
u_a46_Distance 0.643836
u_a46_Landsize 0.116371
u_a46_Price 0.272367
u_a46_Rooms 0.7
u_a46_YearBuilt 0.203252
u_a47_Bathroom 0.0
u_a47_Bedroom2 0.1
u_a47_BuildingArea 0.338945
u_a47_Car 0.4
u_a47_Distance 0.399543
u_a47_Landsize 0.0311111
u_a47_Price 0.578644
u_a47_Rooms 0.156426
u_a47_YearBuilt 0.325203
u_a48_Bathroom 0.0
u_a48_Bedroom2 0.1
u_a48_BuildingArea 0.631569
u_a48_Car 0.4
u_a48_Distance 1.0
u_a48_Landsize 0.0462963
u_a48_Price 0.27417
u_a48_Rooms 0.156426
u_a48_YearBuilt 0.682927
u_a49_Bathroom 0.25
u_a49_Bedroom2 0.3
u_a49_BuildingArea 0.765897
u_a49_Car 0.5
u_a49_Distance 0.347032
u_a49_Landsize 0.273051
u_a49_Price 0.238095
u_a49_Rooms 0.8
u_a49_YearBuilt 0.325203
u_a4_Bathroom 0.25
u_a4_Bedroom2 0.2
u_a4_BuildingArea 0.736047
u_a4_Car 0.4
u_a4_Distance 0.609589
u_a4_Landsize 0.108451
u_a4_Price 0.31746
u_a4_Rooms 0.7
u_a4_YearBuilt 0.829268
u_a50_Bathroom 0.25
u_a50_Bedroom2 0.2
u_a50_BuildingArea 0.7603
u_a50_Car 0.6
u_a50_Distance 0.452055
u_a50_Landsize 0.289236
u_a50_Price 0.25012
u_a50_Rooms 0.7
u_a50_YearBuilt 0.95122
u_a5_Bathroom 1.0
u_a5_Bedroom2 0.3
u_a5_BuildingArea 1.0
u_a5_Car 0.5
u_a5_Distance 0.513699
u_a5_Landsize 0.227253
u_a5_Price 0.0276575
u_a5_Rooms 0.8
u_a5_YearBuilt 0.162602
u_a6_Bathroom 0.0
u_a6_Bedroom2 0.2
u_a6_BuildingArea 0.596121
u_a6_Car 0.7
u_a6_Distance 0.375571
u_a6_Landsize 0.248602
u_a6_Price 0.389129
u_a6_Rooms 0.7
u_a6_YearBuilt 0.243902
u_a7_Bathroom 0.25
u_a7_Bedroom2 0.2
u_a7_BuildingArea 0.676345
u_a7_Car 0.0
u_a7_Distance 0.828767
u_a7_Landsize 0.0733333
u_a7_Price 0.21164
u_a7_Rooms 0.7
u_a7_YearBuilt 0.0813008
u_a8_Bathroom 0.0
u_a8_Bedroom2 0.1
u_a8_BuildingArea 0.426414
u_a8_Car 0.6
u_a8_Distance 0.424658
u_a8_Landsize 0.221054
u_a8_Price 0.582973
u_a8_Rooms 0.156426
u_a8_YearBuilt 0.243902
u_a9_Bathroom 0.25
u_a9_Bedroom2 0.2
u_a9_BuildingArea 0.653957
u_a9_Car 0.5
u_a9_Distance 0.60274
u_a9_Landsize 0.255834
u_a9_Price 0.292569
u_a9_Rooms 0.7
u_a9_YearBuilt 0.365854
w_Bathroom 0.0222222
w_Bedroom2 0.0222222
w_BuildingArea 0.0765359
w_Car 0.4
w_Distance 0.0342466
w_Landsize 0.0222222
w_Price 0.0222222
w_Rooms 0.156426
w_YearBuilt 0.243902
wu_a10_Bathroom 0.0
wu_a10_Bedroom2 0.0222222
wu_a10_BuildingArea 0.0765359
wu_a10_Car 0.4
wu_a10_Distance 0.0342466
wu_a10_Landsize 0.0222222
wu_a10_Price 0.0222222
wu_a10_Rooms 0.156426
wu_a10_YearBuilt 0.243902
wu_a11_Bathroom 0.0
wu_a11_Bedroom2 0.0
wu_a11_BuildingArea 0.0
wu_a11_Car 0.0
wu_a11_Distance 0.0
wu_a11_Landsize 0.0
wu_a11_Price 0.0
wu_a11_Rooms 0.0
wu_a11_YearBuilt 0.001
wu_a12_Bathroom 0.0
wu_a12_Bedroom2 0.0
wu_a12_BuildingArea 0.0
wu_a12_Car 0.0
wu_a12_Distance 0.0
wu_a12_Landsize 0.0
wu_a12_Price 0.0
wu_a12_Rooms 0.0
wu_a12_YearBuilt 0.0
wu_a13_Bathroom 0.0
wu_a13_Bedroom2 0.0
wu_a13_BuildingArea 0.0
wu_a13_Car 0.0
wu_a13_Distance 0.0
wu_a13_Landsize 0.0
wu_a13_Price 0.0
wu_a13_Rooms 0.0
wu_a13_YearBuilt 0.0
wu_a14_Bathroom 0.0
wu_a14_Bedroom2 0.0
wu_a14_BuildingArea 0.0
wu_a14_Car 0.0
wu_a14_Distance 0.0
wu_a14_Landsize 0.0
wu_a14_Price 0.0
wu_a14_Rooms 0.0
wu_a14_YearBuilt 0.0
wu_a15_Bathroom 0.0222222
wu_a15_Bedroom2 0.0222222
wu_a15_BuildingArea 0.0765359
wu_a15_Car 0.4
wu_a15_Distance 0.0342466
wu_a15_Landsize 0.0
wu_a15_Price 0.0222222
wu_a15_Rooms 0.156426
wu_a15_YearBuilt 0.243902
wu_a16_Bathroom 0.0
wu_a16_Bedroom2 0.0
wu_a16_BuildingArea 0.0
wu_a16_Car 0.0
wu_a16_Distance 0.0
wu_a16_Landsize 0.0
wu_a16_Price 0.0
wu_a16_Rooms 0.0
wu_a16_YearBuilt 0.0
wu_a17_Bathroom 0.0
wu_a17_Bedroom2 0.0
wu_a17_BuildingArea 0.0
wu_a17_Car 0.0
wu_a17_Distance 0.0
wu_a17_Landsize 0.0
wu_a17_Price 0.0
wu_a17_Rooms 0.0
wu_a17_YearBuilt 0.0
wu_a18_Bathroom 0.0222222
wu_a18_Bedroom2 0.0
wu_a18_BuildingArea 0.0
wu_a18_Car 0.0
wu_a18_Distance 0.0
wu_a18_Landsize 0.0
wu_a18_Price 0.0
wu_a18_Rooms 0.0
wu_a18_YearBuilt 0.0487805
wu_a19_Bathroom 0.0
wu_a19_Bedroom2 0.0
wu_a19_BuildingArea 0.0
wu_a19_Car 0.0
wu_a19_Distance 0.0
wu_a19_Landsize 0.0
wu_a19_Price 0.0
wu_a19_Rooms 0.0
wu_a19_YearBuilt 0.0
wu_a1_Bathroom 0.0222222
wu_a1_Bedroom2 0.0222222
wu_a1_BuildingArea 0.0765359
wu_a1_Car 0.4
wu_a1_Distance 0.0342466
wu_a1_Landsize 0.0222222
wu_a1_Price 0.0222222
wu_a1_Rooms 0.155426
wu_a1_YearBuilt 0.243902
wu_a20_Bathroom 0.0
wu_a20_Bedroom2 0.0222222
wu_a20_BuildingArea 0.0765359
wu_a20_Car 0.4
wu_a20_Distance 0.0342466
wu_a20_Landsize 0.0222222
wu_a20_Price 0.0222222
wu_a20_Rooms 0.156426
wu_a20_YearBuilt 0.243902
wu_a21_Bathroom 0.0222222
wu_a21_Bedroom2 0.0222222
wu_a21_BuildingArea 0.0755359
wu_a21_Car 0.4
wu_a21_Distance 0.0342466
wu_a21_Landsize 0.0222222
wu_a21_Price 0.0222222
wu_a21_Rooms 0.156426
wu_a21_YearBuilt 0.243902
wu_a22_Bathroom 0.0
wu_a22_Bedroom2 0.0222222
wu_a22_BuildingArea 0.0765359
wu_a22_Car 0.4
wu_a22_Distance 0.0342466
wu_a22_Landsize 0.0222222
wu_a22_Price 0.0222222
wu_a22_Rooms 0.156426
wu_a22_YearBuilt 0.243902
wu_a23_Bathroom 0.0
wu_a23_Bedroom2 0.0
wu_a23_BuildingArea 0.0
wu_a23_Car 0.0
wu_a23_Distance 0.0
wu_a23_Landsize 0.0
wu_a23_Price 0.0
wu_a23_Rooms 0.0
wu_a23_YearBuilt 0.001
wu_a24_Bathroom 0.0
wu_a24_Bedroom2 0.0
wu_a24_BuildingArea 0.0
wu_a24_Car 0.0
wu_a24_Distance 0.0
wu_a24_Landsize 0.0
wu_a24_Price 0.0
wu_a24_Rooms 0.0
wu_a24_YearBuilt 0.001
wu_a25_Bathroom 0.0
wu_a25_Bedroom2 0.0222222
wu_a25_BuildingArea 0.0765359
wu_a25_Car 0.4
wu_a25_Distance 0.0342466
wu_a25_Landsize 0.0222222
wu_a25_Price 0.0222222
wu_a25_Rooms 0.156426
wu_a25_YearBuilt 0.243902
wu_a26_Bathroom 0.0222222
wu_a26_Bedroom2 0.0
wu_a26_BuildingArea 0.0
wu_a26_Car 0.0
wu_a26_Distance 0.0
wu_a26_Landsize 0.0
wu_a26_Price 0.0
wu_a26_Rooms 0.0937961
wu_a26_YearBuilt 0.146341
wu_a27_Bathroom 0.0222222
wu_a27_Bedroom2 0.0222222
wu_a27_BuildingArea 0.0765359
wu_a27_Car 0.4
wu_a27_Distance 0.0342466
wu_a27_Landsize 0.0222222
wu_a27_Price 0.0222222
wu_a27_Rooms 0.156426
wu_a27_YearBuilt 0.243902
wu_a28_Bathroom 0.0
wu_a28_Bedroom2 0.0
wu_a28_BuildingArea 0.0
wu_a28_Car 0.0
wu_a28_Distance 0.0
wu_a28_Landsize 0.0
wu_a28_Price 0.0164502
wu_a28_Rooms 0.0
wu_a28_YearBuilt 0.0
wu_a29_Bathroom 0.0
wu_a29_Bedroom2 0.0
wu_a29_BuildingArea 0.0
wu_a29_Car 0.0
wu_a29_Distance 0.0
wu_a29_Landsize 0.0
wu_a29_Price 0.0
wu_a29_Rooms 0.0
wu_a29_YearBuilt 0.0
wu_a2_Bathroom 0.0
wu_a2_Bedroom2 0.0
wu_a2_BuildingArea 0.0
wu_a2_Car 0.4
wu_a2_Distance 0.0
wu_a2_Landsize 0.0
wu_a2_Price 0.0
wu_a2_Rooms 0.0
wu_a2_YearBuilt 0.0
wu_a30_Bathroom 0.0
wu_a30_Bedroom2 0.0
wu_a30_BuildingArea 0.0
wu_a30_Car 0.0
wu_a30_Distance 0.0
wu_a30_Landsize 0.0
wu_a30_Price 0.0
wu_a30_Rooms 0.0
wu_a30_YearBuilt 0.001
wu_a31_Bathroom 0.0222222
wu_a31_Bedroom2 0.0222222
wu_a31_BuildingArea 0.0765359
wu_a31_Car 0.4
wu_a31_Distance 0.0342466
wu_a31_Landsize 0.0
wu_a31_Price 0.0222222
wu_a31_Rooms 0.156426
wu_a31_YearBuilt 0.243902
wu_a32_Bathroom 0.0
wu_a32_Bedroom2 0.0
wu_a32_BuildingArea 0.0
wu_a32_Car 0.0
wu_a32_Distance 0.0
wu_a32_Landsize 0.0
wu_a32_Price 0.0
wu_a32_Rooms 0.0
wu_a32_YearBuilt 0.243902
wu_a33_Bathroom 0.0
wu_a33_Bedroom2 0.0
wu_a33_BuildingArea 0.0
wu_a33_Car 0.0
wu_a33_Distance 0.0
wu_a33_Landsize 0.0
wu_a33_Price 0.0
wu_a33_Rooms 0.0
wu_a33_YearBuilt 0.0
wu_a34_Bathroom 0.0
wu_a34_Bedroom2 0.0
wu_a34_BuildingArea 0.0
wu_a34_Car 0.0
wu_a34_Distance 0.0
wu_a34_Landsize 0.0
wu_a34_Price 0.0
wu_a34_Rooms 0.0
wu_a34_YearBuilt 0.0
wu_a35_Bathroom 0.0
wu_a35_Bedroom2 0.0
wu_a35_BuildingArea 0.0
wu_a35_Car 0.0
wu_a35_Distance 0.0
wu_a35_Landsize 0.0
wu_a35_Price 0.0
wu_a35_Rooms 0.0
wu_a35_YearBuilt 0.0487805
wu_a36_Bathroom 0.0
wu_a36_Bedroom2 0.0222222
wu_a36_BuildingArea 0.0765359
wu_a36_Car 0.4
wu_a36_Distance 0.0342466
wu_a36_Landsize 0.0222222
wu_a36_Price 0.0222222
wu_a36_Rooms 0.156426
wu_a36_YearBuilt 0.243902
wu_a37_Bathroom 0.0
wu_a37_Bedroom2 0.0
wu_a37_BuildingArea 0.0
wu_a37_Car 0.0
wu_a37_Distance 0.0
wu_a37_Landsize 0.0
wu_a37_Price 0.0
wu_a37_Rooms 0.0
wu_a37_YearBuilt 0.0
wu_a38_Bathroom 0.0
wu_a38_Bedroom2 0.0
wu_a38_BuildingArea 0.0
wu_a38_Car 0.0
wu_a38_Distance 0.0
wu_a38_Landsize 0.0
wu_a38_Price 0.0
wu_a38_Rooms 0.0
wu_a38_YearBuilt 0.0
wu_a39_Bathroom 0.0222222
wu_a39_Bedroom2 0.0222222
wu_a39_BuildingArea 0.0765359
wu_a39_Car 0.4
wu_a39_Distance 0.0342466
wu_a39_Landsize 0.0222222
wu_a39_Price 0.0222222
wu_a39_Rooms 0.156426
wu_a39_YearBuilt 0.243902
wu_a3_Bathroom 0.0
wu_a3_Bedroom2 0.0222222
wu_a3_BuildingArea 0.0765359
wu_a3_Car 0.4
wu_a3_Distance 0.0342466
wu_a3_Landsize 0.0222222
wu_a3_Price 0.0222222
wu_a3_Rooms 0.156426
wu_a3_YearBuilt 0.243902
wu_a40_Bathroom 0.0222222
wu_a40_Bedroom2 0.0222222
wu_a40_BuildingArea 0.0765359
wu_a40_Car 0.4
wu_a40_Distance 0.0342466
wu_a40_Landsize 0.0222222
wu_a40_Price 0.0222222
wu_a40_Rooms 0.156426
wu_a40_YearBuilt 0.243902
wu_a41_Bathroom 0.0
wu_a41_Bedroom2 0.0
wu_a41_BuildingArea 0.0
wu_a41_Car 0.0
wu_a41_Distance 0.0
wu_a41_Landsize 0.0
wu_a41_Price 0.0
wu_a41_Rooms 0.0
wu_a41_YearBuilt 0.002
wu_a42_Bathroom 0.0
wu_a42_Bedroom2 0.0
wu_a42_BuildingArea 0.0
wu_a42_Car 0.0
wu_a42_Distance 0.0
wu_a42_Landsize 0.0
wu_a42_Price 0.0
wu_a42_Rooms 0.0
wu_a42_YearBuilt 0.0
wu_a43_Bathroom 0.0
wu_a43_Bedroom2 0.0
wu_a43_BuildingArea 0.0765359
wu_a43_Car 0.4
wu_a43_Distance 0.0342466
wu_a43_Landsize 0.0222222
wu_a43_Price 0.0222222
wu_a43_Rooms 0.0
wu_a43_YearBuilt 0.243902
wu_a44_Bathroom 0.0
wu_a44_Bedroom2 0.0
wu_a44_BuildingArea 0.0
wu_a44_Car 0.0
wu_a44_Distance 0.0
wu_a44_Landsize 0.0
wu_a44_Price 0.0
wu_a44_Rooms 0.0
wu_a44_YearBuilt 0.0
wu_a45_Bathroom 0.0222222
wu_a45_Bedroom2 0.0222222
wu_a45_BuildingArea 0.0765359
wu_a45_Car 0.4
wu_a45_Distance 0.0342466
wu_a45_Landsize 0.0222222
wu_a45_Price 0.0222222
wu_a45_Rooms 0.156426
wu_a45_YearBuilt 0.243902
wu_a46_Bathroom 0.0
wu_a46_Bedroom2 0.0
wu_a46_BuildingArea 0.0
wu_a46_Car 0.0
wu_a46_Distance 0.0
wu_a46_Landsize 0.0
wu_a46_Price 0.0
wu_a46_Rooms 0.0
wu_a46_YearBuilt 0.0
wu_a47_Bathroom 0.0
wu_a47_Bedroom2 0.0222222
wu_a47_BuildingArea 0.0765359
wu_a47_Car 0.4
wu_a47_Distance 0.0342466
wu_a47_Landsize 0.0222222
wu_a47_Price 0.0222222
wu_a47_Rooms 0.156426
wu_a47_YearBuilt 0.243902
wu_a48_Bathroom 0.0
wu_a48_Bedroom2 0.0
wu_a48_BuildingArea 0.0
wu_a48_Car 0.0
wu_a48_Distance 0.0342466
wu_a48_Landsize 0.0
wu_a48_Price 0.0
wu_a48_Rooms 0.0
wu_a48_YearBuilt 0.0
wu_a49_Bathroom 0.0222222
wu_a49_Bedroom2 0.0222222
wu_a49_BuildingArea 0.0745359
wu_a49_Car 0.4
wu_a49_Distance 0.0342466
wu_a49_Landsize 0.0222222
wu_a49_Price 0.0222222
wu_a49_Rooms 0.156426
wu_a49_YearBuilt 0.243902
wu_a4_Bathroom 0.0222222
wu_a4_Bedroom2 0.0222222
wu_a4_BuildingArea 0.0765359
wu_a4_Car 0.4
wu_a4_Distance 0.0342466
wu_a4_Landsize 0.0222222
wu_a4_Price 0.0222222
wu_a4_Rooms 0.156426
wu_a4_YearBuilt 0.243902
wu_a50_Bathroom 0.0222222
wu_a50_Bedroom2 0.0222222
wu_a50_BuildingArea 0.0755359
wu_a50_Car 0.4
wu_a50_Distance 0.0342466
wu_a50_Landsize 0.0222222

In [240]:
utilities = []
for var in model2.variables():
    if 'U_' in var.name:
        utilities.append((var.name, var.value()))
utilities.sort(key = lambda x: x[1])
utilities

[('U_a12', 0.0),
 ('U_a13', 0.0),
 ('U_a14', 0.0),
 ('U_a16', 0.0),
 ('U_a17', 0.0),
 ('U_a19', 0.0),
 ('U_a29', 0.0),
 ('U_a33', 0.0),
 ('U_a34', 0.0),
 ('U_a37', 0.0),
 ('U_a38', 0.0),
 ('U_a42', 0.0),
 ('U_a44', 0.0),
 ('U_a46', 0.0),
 ('U_a7', 0.0),
 ('U_a11', 0.001),
 ('U_a23', 0.001),
 ('U_a24', 0.001),
 ('U_a30', 0.001),
 ('U_a41', 0.002),
 ('U_a28', 0.0164502),
 ('U_a48', 0.0342466),
 ('U_a35', 0.0487805),
 ('U_a18', 0.0710027),
 ('U_a32', 0.243902),
 ('U_a9', 0.243902),
 ('U_a5', 0.26136),
 ('U_a26', 0.26236),
 ('U_a6', 0.343902),
 ('U_a2', 0.4),
 ('U_a43', 0.799129),
 ('U_a10', 0.977778),
 ('U_a15', 0.977778),
 ('U_a20', 0.977778),
 ('U_a22', 0.977778),
 ('U_a25', 0.977778),
 ('U_a3', 0.977778),
 ('U_a31', 0.977778),
 ('U_a36', 0.977778),
 ('U_a47', 0.977778),
 ('U_a8', 0.977778),
 ('U_a49', 0.998),
 ('U_a1', 0.999),
 ('U_a21', 0.999),
 ('U_a50', 0.999),
 ('U_a27', 1.0),
 ('U_a39', 1.0),
 ('U_a4', 1.0),
 ('U_a40', 1.0),
 ('U_a45', 1.0)]

In [241]:
lambdas = [] # lambdas - values at breakpoints
for var in model2.variables():
    if 'lambda' in var.name:
        lambdas.append((var.name, var.value()))
lambdas.sort(key = lambda x: x[0])
lambdas

[('lambda_Bathroom_0', 0.0),
 ('lambda_Bathroom_1', 0.1),
 ('lambda_Bathroom_2', 0.2),
 ('lambda_Bathroom_3', 0.3),
 ('lambda_Bathroom_4', 0.4),
 ('lambda_Bathroom_5', 1.0),
 ('lambda_Bedroom2_0', 0.0),
 ('lambda_Bedroom2_1', 0.1),
 ('lambda_Bedroom2_2', 0.2),
 ('lambda_Bedroom2_3', 0.3),
 ('lambda_Bedroom2_4', 0.4),
 ('lambda_Bedroom2_5', 1.0),
 ('lambda_BuildingArea_0', 0.0),
 ('lambda_BuildingArea_1', 0.586047),
 ('lambda_BuildingArea_2', 0.686047),
 ('lambda_BuildingArea_3', 0.786047),
 ('lambda_BuildingArea_4', 0.886047),
 ('lambda_BuildingArea_5', 1.0),
 ('lambda_Car_0', 0.0),
 ('lambda_Car_1', 0.4),
 ('lambda_Car_2', 0.5),
 ('lambda_Car_3', 0.6),
 ('lambda_Car_4', 0.7),
 ('lambda_Car_5', 1.0),
 ('lambda_Distance_0', 1.0),
 ('lambda_Distance_1', 0.4),
 ('lambda_Distance_2', 0.3),
 ('lambda_Distance_3', 0.2),
 ('lambda_Distance_4', 0.1),
 ('lambda_Distance_5', 0.0),
 ('lambda_Landsize_0', 0.0),
 ('lambda_Landsize_1', 0.107556),
 ('lambda_Landsize_2', 0.207556),
 ('lambda_Landsize_3', 0.307556),
 ('lambda_Landsize_4', 0.407556),
 ('lambda_Landsize_5', 1.0),
 ('lambda_Price_0', 1.0),
 ('lambda_Price_1', 0.4),
 ('lambda_Price_2', 0.3),
 ('lambda_Price_3', 0.2),
 ('lambda_Price_4', 0.1),
 ('lambda_Price_5', 0.0),
 ('lambda_Rooms_0', 0.0),
 ('lambda_Rooms_1', 0.156426),
 ('lambda_Rooms_2', 0.7),
 ('lambda_Rooms_3', 0.8),
 ('lambda_Rooms_4', 0.9),
 ('lambda_Rooms_5', 1.0),
 ('lambda_YearBuilt_0', 0.0),
 ('lambda_YearBuilt_1', 0.1),
 ('lambda_YearBuilt_2', 0.2),
 ('lambda_YearBuilt_3', 0.3),
 ('lambda_YearBuilt_4', 0.4),
 ('lambda_YearBuilt_5', 1.0)]

In [ ]:
min_max = []
for i in range(len(data.columns)):
    mini = 
    maxi = ...
    min_max.append((mini, maxi))